# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0002_auto_20160107_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/users/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/users/profile_pictures'),
        ),
    ]
