# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuit',
            name='video_file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='media/tuits/videos'),
        ),
    ]
