# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 02:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuits', '0002_auto_20151222_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikesTuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date', models.DateTimeField(auto_now_add=True)),
                ('tuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuits.Tuit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
