# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuits', '0003_userlikestuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuit',
            name='is_retuit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tuit',
            name='original_tuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retuited_tuit', to='tuits.Tuit'),
        ),
    ]
