# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuits', '0004_auto_20160105_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuit',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='tuits/images'),
        ),
        migrations.AlterField(
            model_name='tuit',
            name='video_file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='tuits/videos'),
        ),
    ]
